      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sub.txt sub_plain.txt
          git commit -m "Auto update sub configs" || exit 0
          git push

